---
- name: "NOTSCORED | 1.1 | AUDIT | Ensure packages are obtained from authorized repositories"
  block:
      - name: "NOTSCORED | 1.1 | AUDIT | Ensure packages are obtained from authorized repositories | Get repo list RHEL8"
        shell: dnf repolist all | grep enabled
        changed_when: false
        failed_when: false
        register: pgs12cis_1_1_enabled_repos_rh8
        when:
          - ansible_distribution_file_variety == "RedHat"
          - ansible_distribution_major_version == "8"

      - name: "NOTSCORED | 1.1 | AUDIT | Ensure packages are obtained from authorized repositories | Get repo list RHEL7"
        shell: yum repolist all | grep enabled
        changed_when: false
        failed_when: false
        register: pgs12cis_1_1_enabled_repos_rh7
        when:
          - ansible_distribution_file_variety == "RedHat"
          - ansible_distribution_major_version == "7"

      - name: "NOTSCORED | 1.1 | AUDIT | Ensure packages are obtained from authorized repositories | Show repo list RHEL8"
        debug:
            msg:
                - "Alert! Below are the enabled repo's. Please review to confirm these are authorized repositories"
                - "{{ pgs12cis_1_1_enabled_repos_rh8.stdout_lines }}"
        when:
          - ansible_distribution_file_variety == "RedHat"
          - ansible_distribution_major_version == "8"

      - name: "NOTSCORED | 1.1 | AUDIT | Ensure packages are obtained from authorized repositories | Show repo list RHEL8"
        debug:
            msg:
                - "Alert! Below are the enabled repo's. Please review to confirm these are authorized repositories"
                - "{{ pgs12cis_1_1_enabled_repos_rh7.stdout_lines }}"
        when:
          - ansible_distribution_file_variety == "RedHat"
          - ansible_distribution_major_version == "7"
  when:
      - pgs12cis_rule_1_1
  tags:
      - level1-postgresql
      - notscored
      - audit
      - rule_1.1

- name: "NOTSCORED | 1.2 | AUDIT | Ensure Installation of Binary Packages"
  block:
      - name: "NOTSCORED | 1.2 | AUDIT | Ensure Installation of Binary Packages | Get installed packages and repo RHEL8"
        shell: dnf info $(rpm -qa|grep postgres) | egrep '^Name|^Version|^From'
        changed_when: false
        failed_when: false
        register: pgs12cis_1_2_installed_pckg_rpm_rh8
        when:
          - ansible_distribution_file_variety == "RedHat"
          - ansible_distribution_major_version == "8"

      - name: "NOTSCORED | 1.2 | AUDIT | Ensure Installation of Binary Packages | Get installed packages and repo RHEL7"
        shell: yum info $(rpm -qa|grep postgres) | egrep '^Name|^Version|^From'
        changed_when: false
        failed_when: false
        register: pgs12cis_1_2_installed_pckg_rpm_rh7
        when:
          - ansible_distribution_file_variety == "RedHat"
          - ansible_distribution_major_version == "7"

      - name: "NOTSCORED | 1.2 | AUDIT | Ensure Installation of Binary Packages | Show installed packages and repo RHEL8"
        debug:
            msg:
                - "Alert! Below are the installed postgres packages and where they came from"
                - "Please review and if the expected binary packages are not installed or did not come from an appropriate repo, this is a fail"
                - "{{ pgs12cis_1_2_installed_pckg_rpm_rh8.stdout_lines }}"
        when:
          - ansible_distribution_file_variety == "RedHat"
          - ansible_distribution_major_version == "8"

      - name: "NOTSCORED | 1.2 | AUDIT | Ensure Installation of Binary Packages | Show installed packages and repo RHEL7"
        debug:
            msg:
                - "Alert! Below are the installed postgres packages and where they came from"
                - "Please review and if the expected binary packages are not installed or did not come from an appropriate repo, this is a fail"
                - "{{ pgs12cis_1_2_installed_pckg_rpm_rh7.stdout_lines }}"
        when:
          - ansible_distribution_file_variety == "RedHat"
          - ansible_distribution_major_version == "7"
  when:
      - pgs12cis_rule_1_2
  tags:
      - level-postgresqlonlinux
      - notscored
      - audit
      - rule_1.2

- name: "NOTSCORED | 1.3 | AUDIT | Ensure Installation of Community Packages"
  block:
      - name: "NOTSCORED | 1.3 | AUDIT | Ensure Installation of Community Packages | Get installed packages and repo RHEL8"
        shell: dnf info $(rpm -qa|grep postgres) | egrep '^Name|^Version|^From'
        changed_when: false
        failed_when: false
        register: pgs12cis_1_3_installed_pckg_rpm_rh8
        when:
          - ansible_distribution_file_variety == "RedHat"
          - ansible_distribution_major_version == "8"

      - name: "NOTSCORED | 1.3 | AUDIT | Ensure Installation of Community Packages | Get installed packages and repo RHEL7"
        shell: yum info $(rpm -qa|grep postgres) | egrep '^Name|^Version|^From'
        changed_when: false
        failed_when: false
        register: pgs12cis_1_3_installed_pckg_rpm_rh7
        when:
          - ansible_distribution_file_variety == "RedHat"
          - ansible_distribution_major_version == "7"

      - name: "NOTSCORED | 1.3 | AUDIT | Ensure Installation of Community Packages | Show installed packages and repo RHEL8"
        debug:
            msg:
                - "Alert! Below are the installed postgres packages and where they came from"
                - "Please review and if the expected community packages are not installed or did not come from the PGDG repo, this is a fail"
                - "{{ pgs12cis_1_3_installed_pckg_rpm_rh8.stdout_lines }}"
        when:
          - ansible_distribution_file_variety == "RedHat"
          - ansible_distribution_major_version == "8"

      - name: "NOTSCORED | 1.3 | AUDIT | Ensure Installation of Community Packages | Show installed packages and repo RHEL7"
        debug:
            msg:
                - "Alert! Below are the installed postgres packages and where they came from"
                - "Please review and if the expected community packages are not installed or did not come from an PGDG repo, this is a fail"
                - "{{ pgs12cis_1_3_installed_pckg_rpm_rh7.stdout_lines }}"
        when:
          - ansible_distribution_file_variety == "RedHat"
          - ansible_distribution_major_version == "7"
  when:
      - pgs12cis_rule_1_3
  tags:
      - level-postgresqlonlinux
      - notscored
      - audit
      - rule_1.3

- name: "SCORED | 1.4 | PATCH | Ensure systemd Service Files Are Enabled"
  service:
      name: postgresql-12
      enabled: true
  when:
      - pgs12cis_rule_1_4
  tags:
      - level-postgresqlonlinux
      - scored
      - patch
      - rule_1.4

- name: "SCORED | 1.5 | PATCH | Ensure Data Cluster Initialized Successfully"
  shell: 'PGSETUP_INITDB_OPTIONS="-k" /usr/pgsql-12/bin/postgresql-12-setup initdb'
  changed_when: '"OK" in pgs12cis_1_5_db_initialize.stdout'
  failed_when: false
  register: pgs12cis_1_5_db_initialize
  when:
      - pgs12cis_rule_1_5
  tags:
      - level-postgresqlonlinux
      - scored
      - patch
      - rule_1.5
