---
- name: import preliminary tasks
  ansible.builtin.import_tasks: prelim.yml

- name: RedHat Fixes
  ansible.builtin.import_tasks: cis_pgs12_redhat_fixes.yml
  when:
      - ansible_distribution_file_variety == 'RedHat'
      - ansible_distribution_major_version == "7" or
        ansible_distribution_major_version == "8"
  tags:
      - RedHat
      - CentOS

- name: Ubuntu Fixes
  ansible.builtin.import_tasks: cis_pgs12_ubuntu_fixes.yml
  when:
      - ansible_distribution == 'Ubuntu'
      - ansible_distribution_major_version == "16" or
        ansible_distribution_major_version == "18" or
        ansible_distribution_major_version == "20"
  tags:
      - Ubuntu

- name: If Warnings found Output count and control IDs affected
  ansible.builtin.debug:
      msg: "You have {{ warn_count }} Warning(s) that require investigating that are related to the following benchmark ID(s) {{ warn_control_list }}"
  when: warn_count != 0
  tags:
      - always
