---
- name: import preliminary tasks
  import_tasks: prelim.yml

- name: RedHat Fixes
  import_tasks: cis_pgs12_redhat_fixes.yml
  when: ansible_distribution_file_variety == 'RedHat'
  tags:
      - RedHat
      - CentOS

- name: Ubuntu Fixes
  import_tasks: cis_pgs12_ubuntu_fixes.yml
  when: ansible_distribution == 'Ubuntu'
  tags:
      - Ubuntu