---
# - name: "PRELIM | Install and Start PostgreSQL"
#   block:
#       - name: "PRELIM | Install and Start PostgreSQL | Add PostgreSQL Repo RHEL/CentOS 8"
#         dnf:
#           name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
#           state: present
#         when:
#             - ansible_distribution_file_variety == 'RedHat'
#             - ansible_major_verision == 8

#       - name: "PRELIM | Install and Start PostgreSQL | Add PostgreSQL Repo RHEL/CentOS 7"
#         yum:
#             name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
#             state: present
#         when:
#             - ansible_distribution_file_variety == 'RedHat'
#             - ansible_major_verision == 7

#       - name: "PRELIM | Install adn Start PostgreSQL | Disable built in PostgreSQL"
#         shell: dnf -y module disable postgresql
#         register: prelim_disable_pgs_old_rh8
#         changed_when: "'Disabling modules' in prelim_disable_pgs_old_rh8.stdout"
#         when:
#             - ansible_distribution_file_variety == 'RedHat'
#             - ansible_major_verision == 8

#       - name: "PRELIM | Install adn Start PostgreSQL | Install PostgreSQL 12"
#         dnf:
#           name: ['postgresql12', 'postgresql12-server']
#           state: present
#         when:
#             - ansible_distribution_file_variety == 'RedHat'
#             - ansible_major_verision == 8

#       - name: "PRELIM | Install adn Start PostgreSQL | Initialize PostgreSQL 12"
#         command: /usr/pgsql-12/bin/postgresql-12-setup initdb
- name: "PRELIM | Install ACL when needed"
  apt:
      name: acl
      state: present
  when: ansible_distribution == 'Ubuntu'

- name: "PRELIM | Get postgres config file path"
  shell: psql -U postgres -c 'SHOW config_file' | tail -n+3 | head -n 1 | cut -c2-
  changed_when: false
  failed_when: false
  become_user: "{{ pgs12cis_pgs12_usr }}"
  register: pgs12cis_config_file_get

- name: "PRELIM | Get postgres config file path"
  shell: psql -U postgres -c 'SHOW hba_file' | tail -n+3 | head -n 1 | cut -c2-
  changed_when: false
  failed_when: false
  become_user: "{{ pgs12cis_pgs12_usr }}"
  register: pgs12cis_hba_config_file_get

- name: "PRELIM | 2.1 | Get postgresql user home folder"
  shell: "grep {{ pgs12cis_pgs12_usr }} /etc/passwd | cut -f6 -d:"
  changed_when: false
  failed_when: false
  register: pgs12cis_pgs12_usr_home_dir_get
  when:
      - pgs12cis_rule_2_1

- name: "PRELIM | Finding the PostgreSQL Configured Data Directory (PGDATA)"
  block:
      - name: "PRELIM | Finding the PostgreSQL Configured Data Directory (PGDATA) | Get path"
        shell: psql -c 'show data_directory' | tail -n+3 | head -n 1 | cut -c2-
        check_mode: false
        changed_when: false
        register: pgs12cis_pgdata_cmd
        become: true
        become_user: "{{ pgs12cis_pgs12_usr }}"

      - name: "PRELIM | Finding the PostgreSQL Configured Data Directory (PGDATA) | Make var easier to use"
        set_fact:
            pgs12cis_data_folder: "{{ pgs12cis_pgdata_cmd.stdout }}"
  when:
      - pgs12cis_rule_3_1_2

- name: "PRELIM | 6.7 | Check if /boot or /boot/efi reside on separate partitions"
  shell: df --output=target /boot | tail -n 1
  changed_when: false
  check_mode: false
  register: pgs12cis_prelim_boot_part
  when:
      - pgs12cis_rule_6_7
      - pgs12cis_section6

- name: "PRELIM | 6.7 | Check whether machine is UEFI-based"
  stat:
      path: /sys/firmware/efi
  register: pgs12cis_prelim_sys_firmware_efi
  when:
      - pgs12cis_rule_6_7
      - pgs12cis_section6

- name: "PRELIM | 6.8 | Generate Self-Signed Cert"
  block:
      - name: "PRELIM | 6.8 | Generate Self-Signed Cert | Check for existing cert"
        find:
            paths: "{{ pgs12cis_data_folder }}"
            patterns: '*.crt,*.key'
        become_user: "{{ pgs12cis_pgs12_usr }}"
        register: pgs12cis_certs_status

      - name: "PRELIM | 6.8 | Generate Self-Signed Cert | Create self-signed certificates"
        command: 'openssl req -new -x509 -days 365 -nodes -text -out {{ pgs12cis_data_folder }}/server.crt -keyout {{ pgs12cis_data_folder }}/server.key -subj "/CN={{ ansible_nodename }}"'
        when: pgs12cis_certs_status.matched == 0

      - name: "PRELIM | 6.8 | Generate Self-Signed Cert | Set permissions on key file"
        file:
            path: "{{ pgs12cis_data_folder }}/server.key"
            mode: og-rwx
            owner: "{{ pgs12cis_pgs12_usr }}"
            group: "{{ pgs12cis_pgs12_usr }}"
        when: pgs12cis_certs_status.matched == 0
  when:
      - pgs12cis_rule_6_8
      - pgs12cis_section6
      - pgs12cis_create_selfsigned_cert

- name: "PRELIM | 6.9 | Install PostgreSQL contrib package"
  block:
      - name: "PRELIM | 6.9 | Install PostgreSQL contrib package | RHEL 8"
        dnf:
            name: postgresql12-contrib
            state: present
        when: ansible_distribution_major_version == "8"

      - name: "PRELIM | 6.9 | Install PostgreSQL contrib package | RHEL 7"
        yum:
            name: postgresql12-contrib
            state: present
        when: ansible_distribution_major_version == "7"
  when:
      - pgs12cis_rule_6_9
      - pgs12cis_section6
