---

# Section 4
# User Access and Authorization
- name: "4.1 | PATCH | Ensure sudo is configured correctly"
  block:
      - name: "4.1 | PATCH | Ensure sudo is configured correctly | Configure dba to sudoers"
        ansible.builtin.lineinfile:
            path: /etc/sudoers.d/postgres
            regexp: '^%dba ALL='
            line: '%dba ALL=({{ pgs12cis_pgs12_usr }}) PASSWD: ALL'
            create: true

      - name: "4.1 | PATCH | Ensure sudo is configured correctly | Set file permissions"
        ansible.builtin.file:
            path: /etc/sudoers.d/postgres
            mode: 0600
  when:
      - pgs12cis_rule_4_1
  tags:
      - level1-postgresqlonlinux
      - patch
      - rule_4.1
